config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
  end

  resources :posts do
    resources :comments
  end  

  get 'results', to: 'results#index', as: 'results'
  get 'users/show', as: 'user_root'
  
  get 'about', to: "pages#about", as: "about"
  root 'pages#index'
end

app/models/post.rb
class Post < ApplicationRecord

  include PgSearch

  pg_search_scope :search_everywhere, against: [:title, :body]

  belongs_to :user
  has_many :comments

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    # @user = User.find(@post.user_id)
    @comments = Comment.where(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, 'error') %> prohibited this article from being saved:
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
    <%= f.label :title, "Заголовок" %><br>
    <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body, "Текст статті" %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit "Створити статтю" %>
    </p>
<% end %>

app/views/posts/edit.html.erb
  <h1>Редагувати статтю</h1>
    <%= form_for @post do |f| %>
      <p>
      <%= f.label :title, "Заголовок" %><br>
      <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :body, "Текст статті" %><br>
        <%= f.text_area :body %>
      </p>

      <p>
        <%= f.submit "Редагувати статтю" %>
      </p>
      <%= link_to "Повернутися", :back %>
    </div>
  <% end %>

app/views/posts/index.html.erb
  <div class="posts">
    <% @posts.each do |p| %>
        <div class="post-view">
          <p>Заголовок:</p>
          <div class="post-title">
             <%= link_to "#{p.title}", post_path(p) %>
          </div>
          <p>Текст:</p>
          <div class="post-body">
            <%= p.body %>
          </div>
            <% if p.comments.count > 0 %>
              <div class="post-comments">
                <p>Коменти:</p>
                  <% p.comments.each do |comment| %>
                    <div class="post-comment-view">
                      <%= comment.text %>
                    </div>
                  <% end %>
              </div>
            <% end %>
          </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<div class="posts">
  <h1>Нова стаття</h1>

  <%= render 'form' %>

    <%= link_to "Повернутися", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="posts">

    <div class="post-title-show">
      <%= @post.title %>
    </div>

    <div class='post-body-show'>
      <%= @post.body %>    
    </div>
    <p>Автор статті: <%= @post.user_id %></p>
      <% if @comments.count > 0 %>
        <div class="post-comments">
          <p>Коменти:</p><br>
            <% @comments.each do |comment| %>
              <div class="post-comment-user-view">
                Автор: <%= comment.user_id %>
              </div>
              <div class="post-comment-view">
                <p>Текст коменту:</p>
                <%= comment.text %>
              </div>
              <div>
                <%= link_to 'Видалити', [comment.post, comment],
                                               method: :delete,
                                               data: {confirm: 'Впевнені?'} %>
              </div><br>
            <% end %>
        </div>
      <% end %>
      
    <%= link_to "Додати комент", new_post_comment_path(@post) %>
    <%= button_to "Видалити пост", post_path(@post), data: { confirm: "Ви впевнені?" }, method: :delete %>
</div>