config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
  end

  resources :posts do
    resources :comments
  end  

  get 'results', to: 'results#index', as: 'results'
  get 'users/show', as: 'user_root'
  
  get 'about', to: "pages#about", as: "about"
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

  include PgSearch

  pg_search_scope :search_everywhere, against: [:title, :body]

  belongs_to :user
  has_many :comments

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable
         # :omniautable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update) do |u|
        u.permit(:nickname, 
                :email, 
                :password, 
                :current_password, 
                :is_female, :date_of_birth)
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.all  
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def edit
    # render form to browser, who will send to update method 
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.save
      redirect_to @post
    else
      render 'edit'      
    end
  end

  def new
    # render form to browser, who will send to create method 
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_to @post
    else
      render 'new'      
    end
    
  end


  def update
    
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all

    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  def about
  	
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    # @user = User.find(@post.user_id)
    @comments = Comment.where(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @search_results = Post.search_everywhere(params[:query])
  end

  private

  def user_params
    params.require(:user).permit(:email, :nickname)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def show
    @user = current_user
    # @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Народний музей Ізюмщини</title>
  <meta charset="utf-8">
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    'reset', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <div class="wrapper">
      <div class="header">
        <%= form_tag results_path, method: :get, role: 'search' do %>
          <%= text_field_tag :query, params[:query] %>
          <%= submit_tag "Пошук", name: nil %>
        <% end %>
        <ul id="navbar">
          <li><%= link_to "Головна", root_path %></li>
          <li><%= link_to "Статті", posts_path %>
            <% if user_signed_in? %>
              <ul>
                <li><%= link_to "Створити статтю", new_post_path %></li>
              </ul>
            <% end %>
          </li>
          <li><%= link_to "Галерея" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Профіль", user_root_path %>
            <ul>
              <li><%= link_to "Редагувати профіль", edit_user_registration_path %></li>
              <li><%= link_to "Видалити профіль", user_registration_path, :confirm => "Ви впевнені?", :method => :delete %></li>
              <li><%= link_to "Вийти", destroy_user_session_path %></li>
            </ul>
          <% else %>
            <li><%= link_to 'Увійти', new_user_session_path %></li>
            <li><%= link_to 'Зареєструватися', new_user_registration_path %></li>
              <% end %>
          </li>
          <li><%= link_to "Про нас", about_path %></li>
        </ul>
      </div>
      <%= yield %>
      <div class="footer">
    
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="user-data">
	<h1>Про наше об'єднання</h1>
	<p>Але щоб ви зрозуміли, звідки виникає це хибне уявлення людей, цуратись насолоди і вихваляти страждання, я розкрию перед вами всю картину і роз’ясню, що саме говорив цей чоловік, який відкрив істину, якого я б назвав зодчим щасливого життя. Дійсно, ніхто не відкидає, не зневажає, не уникає насолод тільки через те, що це насолоди, але лише через те, що тих, хто не вміє розумно вдаватися насолоді, осягають великі страждання. Так само як немає нікого, хто полюбивши, вважав за краще і зажадав би саме страждання тільки за те, що це страждання, а не тому, що інший раз виникають такі обставини, коли страждання і біль приносять якесь і чималу насолоду. Якщо скористатися найпростішим прикладом, то хто з нас став би займатися якими б то не було тяжкими фізичними вправами, якщо б це не приносило з собою якоїсь користі? І хто міг би по справедливості дорікнути прагнення до насолоди, яке не несло б з собою ніяких неприємностей, або того, хто уникав би такого страждання, яке не приносило б з собою ніякої насолоди?</p>

	<p>Але ми цураємось і вважаємо, що  заслуговують справедливого обурення ті, хто, піддався звабі і розбещеним спокусам, які дають їм насолоду, і без тями від пристрасті не передбачили, яких страждань і які нещастя на них чекають. Вони винні так само, як і ті, хто через душевну слабкість, тобто через бажання уникнути страждань і болю відмовляється від виконання свого обов’язку. Втім, тут дуже легко і просто провести відмінності, тому що, коли ми вільні і нам надана повна можливість вибору бажаного, коли ніщо не заважає нам робити те, що нам більше подобається, будь яку насолоду слід визнати бажаним, а будь-яке страждання огидним. Але при деяких обставинах – або на вимогу боргу, або в силу якоїсь необхідності часто доводиться забувати про насолоди і не втікати від тягарів. Тому мудрець дотримується в цьому випадку наступного принципу вибору – або, відмовляючись від задоволення, він отримує якісь інші і навіть великі насолоди, або, зазнаючи страждання, він позбавляється від більш жорстоких.</p>
</div>